/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package socket.server;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class App {
    private static final int PORT = 9876;

    public void startServerAndAcceptRequest() throws IOException, ClassNotFoundException {
        ServerSocket server = new ServerSocket(PORT);
        System.out.println("Starting socket server");
        ExecutorService pool = Executors.newFixedThreadPool(1_000);

        while (true) {
            System.out.println("Waiting for the client request");
            Socket socket = server.accept();
            pool.submit(ConnectionHandler.newConnectionHandler(socket));
        }
    }

    public static void main(String[] args) throws IOException, ClassNotFoundException{
        new App().startServerAndAcceptRequest();
    }
}
